# Generated by Django 6.0.5 on 2026-05-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('edad', models.IntegerField(choices=[(5, '5 años'), (6, '6 años'), (7, '7 años')], default=5)),
                ('avatar', models.CharField(choices=[('conejo', 'Conejo'), ('gato', 'Gato'), ('lechuza', 'Lechuza'), ('leon', 'León'), ('oso', 'Oso'), ('panda', 'Panda'), ('Perico', 'Perico'), ('tigre', 'Tigre'), ('zorro', 'Zorro')], default='panda', max_length=20)),
                ('puntos', models.IntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['-puntos'],
            },
        ),
    ]
