# Generated by Django 4.2.16 on 2026-05-12 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(max_length=50)),
                ('puntos_requeridos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ObjetoTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('avatar', 'Avatar'), ('fondo', 'Fondo'), ('accesorio', 'Accesorio')], max_length=20)),
                ('precio', models.IntegerField()),
                ('imagen', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='max_racha',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='racha_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='ultima_actividad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CompraEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='usuarios.estudiante')),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.objetotienda')),
            ],
        ),
        migrations.CreateModel(
            name='InsigniaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtenida', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insignias', to='usuarios.estudiante')),
                ('logro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.logro')),
            ],
            options={
                'unique_together': {('estudiante', 'logro')},
            },
        ),
    ]
