# Generated by Django 4.2.16 on 2026-05-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_estudiante_email_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='avatar',
            field=models.CharField(choices=[('conejo', 'Conejo'), ('gato', 'Gato'), ('lechuza', 'Lechuza'), ('leon', 'León'), ('oso', 'Oso'), ('panda', 'Panda'), ('perico', 'Perico'), ('tigre', 'Tigre'), ('zorro', 'Zorro')], default='panda', max_length=20),
        ),
    ]
