# Generated by Django 4.2.16 on 2026-05-12 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='dificultad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('multiple', 'Opción Múltiple'), ('completar', 'Completar Frase')], default='multiple', max_length=20),
        ),
    ]
