# Generated by Django 4.2.16 on 2026-05-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_libro_autor_edad_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='librojuego',
            name='adivinanzas',
            field=models.JSONField(default=list),
        ),
    ]
