# Generated by Django 6.0.5 on 2026-05-06 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libros', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_obtenidos', models.IntegerField(default=0)),
                ('completado', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='usuarios.estudiante')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='libros.libro')),
            ],
            options={
                'verbose_name': 'Sesión de Actividad',
                'verbose_name_plural': 'Sesiones de Actividad',
                'ordering': ['-fecha'],
            },
        ),
    ]
